<?php

namespace CvBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FamilleCompetenceRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleCompetenceRepository extends EntityRepository {

    /**
     * Retourne les familles de compétence
     */
    public function getByIndice() {

        $qb = $this->_em->createQueryBuilder();

        $qb->select('f')
            ->from($this->_entityName, 'f')
            ->orderBy('f.indice', 'ASC');

        return $qb->getQuery()->getResult();

    }

    /**
     * Retourne les familles de competences et leurs competences
     */
    public function getFamilleCompetenceWithCompetence() {
        $qb = $this->createQueryBuilder('f');
        $qb->join('f.competences', 'com')->addSelect('com');
        return $qb->getQuery()->getArrayResult();
    }
}
