<?php

namespace CvBundle\Repository;

/**
 * FamilleCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
