# app/config/security.yml

security:
  encoders:
    CVUserBundle\Entity\Utilisateur: sha512

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_AUTEUR, TOLE_MODERATEUR]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        pattern: ^/
        anonymous:    true
        provider:     main
        form_login:
          login_path: cv_connexion
          check_path: cv_connexion_check
        logout:
          path:       cv_deconnexion
          target:     /
        remember_me:
          secret:     %secret%

  access_control:
          - { path: ^/administration, roles: ROLE_ADMIN }
