# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_AUTEUR, TOLE_MODERATEUR]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        pattern: ^/
        anonymous:    true
        provider:     in_memory
        form_login:
          login_path: cv_connexion
          check_path: cv_connexion_check
        logout:
          path:       cv_deconnexion
          target:     /

  access_control:
          - { path: ^/administration, roles: ROLE_ADMIN }
