cv_accueil:
    path:     /
    defaults: { _controller: CvBundle:Home:index }
cv_administration:
    path:     /administration
    defaults: { _controller: CvBundle:Home:administration }
cv_experiences:
    path:     /experiences
    defaults: { _controller: CvBundle:Home:experiences }
cv_formations:
    path:     /formations
    defaults: { _controller: CvBundle:Home:formations }
cv_competences:
    path:     /competences
    defaults: { _controller: CvBundle:Home:competences}
cv_competence_ajouter:
    path:     /administration/competence/ajouter
    defaults: { _controller: CvBundle:Competence:ajouter }
cv_famillecompetence_ajouter:
    path:     /administration/famillecompetence/ajouter
    defaults: { _controller: CvBundle:FamilleCompetence:ajouter}
cv_tag_ajouter:
    path:     /administration/tag/ajouter
    defaults: { _controller: CvBundle:Tag:ajouter}
cv_entreprise_ajouter:
    path:     /administration/entreprise/ajouter
    defaults: { _controller: CvBundle:Entreprise:ajouter }
cv_experience_ajouter:
    path:     /administration/experience/ajouter
    defaults: { _controller: CvBundle:Experience:ajouter}
cv_experiences_supprimmer:
    path:     /administration/experiences/supprimer
    defaults: { _controller: CvBundle:Experience:supprimerTous}