services:
  oc_platform.doctrine_listener.application_creation:
    class: CvBundle\DoctrineListeners\EntityUpdateDatemodification
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }